export type MltPrompt = {
  id: string;
  text: string;
  tags?: string[];
};

// Hand-curated prompts. Keep tone friend-group-friendly: no appearance, money,
// relationships, or sensitive topics. Drama lives in the voting, not the prompts.
// All entries lead with "Most likely to" so the host doesn't have to think about prefixing.
export const MLT_PROMPTS: MltPrompt[] = [
  { id: "ghost-group-chat", text: "Most likely to ghost the group chat for 3 days" },
  { id: "show-up-early", text: "Most likely to show up 30 minutes early to everything" },
  { id: "survive-zombie", text: "Most likely to survive a zombie apocalypse" },
  { id: "fall-asleep-movie", text: "Most likely to fall asleep during a movie" },
  { id: "talk-to-stranger", text: "Most likely to strike up a conversation with a stranger" },
  { id: "cry-at-pixar", text: "Most likely to cry at a Pixar movie" },
  { id: "lose-keys", text: "Most likely to lose their keys" },
  { id: "win-trivia", text: "Most likely to win a pub trivia night" },
  { id: "start-band", text: "Most likely to start a band" },
  { id: "become-famous", text: "Most likely to become famous" },
  { id: "run-marathon", text: "Most likely to run a marathon on a whim" },
  { id: "adopt-five-pets", text: "Most likely to adopt five pets" },
  { id: "forget-birthday", text: "Most likely to forget their own birthday" },
  { id: "binge-show", text: "Most likely to binge a whole show in one night" },
  { id: "miss-flight", text: "Most likely to miss a flight" },
  { id: "remember-trivia", text: "Most likely to remember a random fact from 10 years ago" },
  { id: "become-vegan", text: "Most likely to go vegan" },
  { id: "move-abroad", text: "Most likely to pack up and move abroad" },
  { id: "start-business", text: "Most likely to start their own business" },
  { id: "win-cookoff", text: "Most likely to win a cook-off" },
  { id: "burn-water", text: "Most likely to burn water trying to cook" },
  { id: "host-dinner-party", text: "Most likely to host the best dinner party" },
  { id: "give-speech", text: "Most likely to give an unforgettable wedding speech" },
  { id: "send-typo-text", text: "Most likely to send a text full of typos" },
  { id: "voice-of-reason", text: "Most likely to be the voice of reason" },
  { id: "make-everyone-laugh", text: "Most likely to make everyone laugh in any situation" },
  { id: "fix-anything", text: "Most likely to fix something with duct tape" },
  { id: "read-instructions", text: "Most likely to actually read the instructions" },
  { id: "argue-with-gps", text: "Most likely to argue with their GPS" },
  { id: "befriend-cat", text: "Most likely to befriend every cat in the neighborhood" },
  { id: "deep-question", text: "Most likely to ask a deep question at 2am" },
  { id: "leave-on-read", text: "Most likely to leave you on read" },
  { id: "double-text", text: "Most likely to double-text" },
  { id: "tell-bad-joke", text: "Most likely to tell the same joke twice" },
  { id: "explain-it-all", text: "Most likely to explain something in too much detail" },
  { id: "remember-everyones-name", text: "Most likely to remember everyone's name at a party" },
  { id: "make-the-playlist", text: "Most likely to make the road-trip playlist" },
  { id: "diy-disaster", text: "Most likely to attempt a DIY project and regret it" },
  { id: "buy-too-much", text: "Most likely to buy too much at the grocery store" },
  { id: "talk-to-pets", text: "Most likely to hold full conversations with their pets" },
  { id: "win-board-game", text: "Most likely to win a board game by accident" },
  { id: "flip-table-monopoly", text: "Most likely to flip the table during Monopoly" },
  { id: "ace-quiz", text: "Most likely to ace a random online quiz" },
  { id: "fall-down-rabbit-hole", text: "Most likely to fall down a Wikipedia rabbit hole" },
  { id: "wear-same-thing", text: "Most likely to wear the same outfit two days in a row" },
  { id: "lose-bet", text: "Most likely to lose a bet they were sure they'd win" },
  { id: "find-shortcut", text: "Most likely to find a shortcut everywhere" },
  { id: "save-the-day", text: "Most likely to save the day at the last minute" },
  { id: "rebook-vacation", text: "Most likely to rebook the same vacation every year" },
  { id: "try-new-hobby", text: "Most likely to pick up a new hobby every month" },
];
